import { Patient, Appointment, DoctorProfile, ClinicalRecordEntry, ToothCondition } from './types';

export const DEFAULT_DOCTOR_PHOTO_URL = 'https://lh3.googleusercontent.com/aida-public/AB6AXuCvylWKMoYvCZwNKNkTXbyOMgC8KvaKg8SYr8bMcB2-36iXhpVKMq6bVP8FO-W4ef76avVc1hUxciWw6rivN0M5xAdb2VfgJLVACCE0giZjL91FK6Xcmwmzw8EvCdTsaZSaMz9vp4wLQrbjUfjgn5tGcF6ajHSNLV1V-FOQRrYsuA8RPHxbExGzK0pwgWXUAcMibhlE4Fag04yMndy5DXP6B7zLCD4pTaNTZcCQhICZGlQpoAxCvmkjIocBhd2riLs53Iejjaf-NOc';

export const initialDoctorProfile: DoctorProfile = {
  name: 'Dra. Karine Ramos',
  role: 'Cirurgiã-Dentista - Especialista em Ortodontia e Estética',
  cro: 'CRO-SP 148.921',
  email: 'karine@consultorio.com',
  phone: '(85) 988076961',
  clinicName: 'Dra. Karine Nogueira Ramos - Gestão Odontológica',
  avatarUrl: DEFAULT_DOCTOR_PHOTO_URL,
  profile_picture_url: DEFAULT_DOCTOR_PHOTO_URL,
  address: 'Av. Paulista, 1500',
  cep: '01310-100',
  complement: 'Conjunto 121',
  neighborhood: 'Bela Vista',
  city: 'São Paulo',
  state: 'SP',
};

export const initialPatients: Patient[] = [
  {
    id: 'pat-1',
    name: 'Ana Paula Nascimento',
    cpf: '123.456.789-00',
    rg: '28.192.481-2',
    birthDate: '1992-05-14',
    age: 32,
    gender: 'Feminino',
    phone: '(11) 98765-4321',
    whatsapp: '(11) 98765-4321',
    email: 'ana.paula@email.com',
    instagram: '@anapauladesign',
    address: 'Av. Paulista, 1500',
    cep: '01310-100',
    complement: 'Apto 42',
    neighborhood: 'Bela Vista',
    city: 'São Paulo',
    state: 'SP',
    registrationDate: '2023-08-10',
    maritalStatus: 'Casado(a)',
    active: true,
    notes: 'Paciente relata sensibilidade no dente 16. Histórico de bruxismo leve. Usa placa miorrelaxante.',
    lastVisit: 'Ontem',
    initials: 'AN',
    allergies: ['Penicilina'],
    medicalHistory: ['Hipertensão leve sob controle'],
    convenioId: 1,
    convenioName: 'Unimed',
  },
  {
    id: 'pat-2',
    name: 'Ricardo Carvalho',
    cpf: '987.654.321-11',
    rg: '19.482.910-X',
    birthDate: '1985-11-20',
    age: 38,
    gender: 'Masculino',
    phone: '(11) 91234-5678',
    whatsapp: '(11) 91234-5678',
    email: 'ricardo.carvalho@empresa.com.br',
    instagram: '@rcarvalho_dev',
    address: 'Rua Marechal Deodoro, 400',
    cep: '09710-000',
    complement: 'Bloco B, Apto 12',
    neighborhood: 'Centro',
    city: 'São Bernardo',
    state: 'SP',
    registrationDate: '2023-01-15',
    maritalStatus: 'Solteiro(a)',
    active: false,
    notes: 'Tratamento de restauração concluído em outubro de 2023. Aguardando retorno para limpeza semestral.',
    lastVisit: '12 Out 2023',
    initials: 'RC',
    allergies: [],
    medicalHistory: [],
    convenioId: 2,
    convenioName: 'Bradesco Saúde',
  },
  {
    id: 'pat-3',
    name: 'Mariana Souza',
    cpf: '456.123.789-22',
    rg: '42.910.293-8',
    birthDate: '1998-03-08',
    age: 26,
    gender: 'Feminino',
    phone: '(11) 95555-1234',
    whatsapp: '(11) 95555-1234',
    email: 'mariana.souza@gmail.com',
    instagram: '@mari_souza',
    address: 'Rua das Figueiras, 850',
    cep: '09080-300',
    neighborhood: 'Bairro Jardim',
    city: 'Santo André',
    state: 'SP',
    registrationDate: '2023-09-27',
    maritalStatus: 'Solteiro(a)',
    active: true,
    notes: 'Em tratamento ortodôntico (Alinhadores invisíveis). Próxima manutenção agendada para este mês.',
    lastVisit: '3 dias atrás',
    initials: 'MS',
    allergies: ['Dipirona'],
    medicalHistory: [],
    convenioId: 3,
    convenioName: 'Amil',
  },
  {
    id: 'pat-4',
    name: 'Fernando Batista',
    cpf: '321.654.987-44',
    rg: '33.102.948-1',
    birthDate: '1979-09-12',
    age: 44,
    gender: 'Masculino',
    phone: '(11) 94444-8888',
    whatsapp: '(11) 94444-8888',
    email: 'fernando.batista@advocacia.com',
    address: 'Rua Augusta, 2100',
    cep: '01412-000',
    complement: 'Conjunto 81',
    neighborhood: 'Consolação',
    city: 'São Paulo',
    state: 'SP',
    registrationDate: '2023-10-01',
    maritalStatus: 'Casado(a)',
    active: true,
    notes: 'Realizou clareamento a laser hoje. Recomendadas restrições alimentares por 48 horas.',
    lastVisit: 'Hoje',
    initials: 'FB',
    allergies: [],
    medicalHistory: ['Diabetes Tipo 2'],
    convenioId: 1,
    convenioName: 'Unimed',
  },
  {
    id: 'pat-5',
    name: 'Camila Rodrigues',
    cpf: '567.890.123-55',
    rg: '50.192.384-9',
    birthDate: '2001-07-22',
    age: 23,
    gender: 'Feminino',
    phone: '(11) 97777-3322',
    whatsapp: '(11) 97777-3322',
    email: 'camila.rodrigues@hotmail.com',
    address: 'Rua Oscar Freire, 980',
    cep: '01426-000',
    neighborhood: 'Jardins',
    city: 'São Paulo',
    state: 'SP',
    registrationDate: '2024-02-14',
    maritalStatus: 'Solteiro(a)',
    active: true,
    notes: 'Avaliação inicial para lentes de contato dental em porcelana. Molde digital realizado.',
    lastVisit: '5 dias atrás',
    initials: 'CR',
    allergies: [],
    medicalHistory: [],
    convenioId: 5,
    convenioName: 'Porto Seguro Saúde',
  },
  {
    id: 'pat-6',
    name: 'Lucas Eduardo Mendes',
    cpf: '890.123.456-77',
    rg: '38.291.029-4',
    birthDate: '1990-12-03',
    age: 33,
    gender: 'Masculino',
    phone: '(11) 93333-9900',
    whatsapp: '(11) 93333-9900',
    email: 'lucas.mendes@mendeseng.com.br',
    address: 'Av. Ibirapuera, 3100',
    cep: '04029-200',
    neighborhood: 'Moema',
    city: 'São Paulo',
    state: 'SP',
    registrationDate: '2024-01-20',
    maritalStatus: 'Casado(a)',
    active: true,
    notes: 'Encaminhado para endodontia (Tratamento de Canal no dente 26).',
    lastVisit: 'Semana passada',
    initials: 'LM',
    allergies: ['Aspirina'],
    medicalHistory: [],
    convenioId: 1,
    convenioName: 'Unimed',
  },
];

export const initialAppointments: Appointment[] = [
  {
    id: 'app-1',
    patientId: 'pat-4',
    patientName: 'Fernando Batista',
    patientPhone: '(11) 94444-8888',
    date: '2026-07-23',
    time: '09:00',
    durationMinutes: 45,
    procedure: 'Clareamento Dental',
    status: 'Concluído',
    notes: 'Sessão 2 de clareamento realizada com sucesso.',
    value: 650,
    convenioId: 1,
    convenioName: 'Unimed',
  },
  {
    id: 'app-2',
    patientId: 'pat-1',
    patientName: 'Ana Paula Nascimento',
    patientPhone: '(11) 98765-4321',
    date: '2026-07-23',
    time: '10:30',
    durationMinutes: 60,
    procedure: 'Restauração em Resina',
    status: 'Em Atendimento',
    notes: 'Restauração estética no dente 16.',
    value: 350,
    convenioId: 1,
    convenioName: 'Unimed',
  },
  {
    id: 'app-3',
    patientId: 'pat-3',
    patientName: 'Mariana Souza',
    patientPhone: '(11) 95555-1234',
    date: '2026-07-23',
    time: '14:00',
    durationMinutes: 30,
    procedure: 'Manutenção Ortodôntica',
    status: 'Confirmado',
    notes: 'Troca de alinhadores transparentes.',
    value: 280,
    convenioId: 3,
    convenioName: 'Amil',
  },
  {
    id: 'app-4',
    patientId: 'pat-5',
    patientName: 'Camila Rodrigues',
    patientPhone: '(11) 97777-3322',
    date: '2026-07-23',
    time: '15:30',
    durationMinutes: 60,
    procedure: 'Prova de Lentes de Contato',
    status: 'Aguardando',
    notes: 'Prova do mock-up e escolha da escala de cor (BL2).',
    value: 1200,
    convenioId: 5,
    convenioName: 'Porto Seguro Saúde',
  },
  {
    id: 'app-5',
    patientId: 'pat-6',
    patientName: 'Lucas Eduardo Mendes',
    patientPhone: '(11) 93333-9900',
    date: '2026-07-24',
    time: '11:00',
    durationMinutes: 90,
    procedure: 'Tratamento de Canal (Endodontia)',
    status: 'Confirmado',
    notes: 'Primeira sessão do dente 26.',
    value: 850,
    convenioId: 1,
    convenioName: 'Unimed',
  },
];

export const initialClinicalRecords: ClinicalRecordEntry[] = [
  {
    id: 'rec-1',
    patientId: 'pat-1',
    date: '2026-07-22',
    dentistName: 'Dra. Karine Ramos',
    procedureDone: 'Avaliação Clínica e Radiografia Periapical',
    toothNumber: 16,
    clinicalNotes: 'Identificada cárie oclusal leve no dente 16. Agendada restauração em resina composta no tom A2.',
    cost: 150,
  },
  {
    id: 'rec-2',
    patientId: 'pat-4',
    date: '2026-07-23',
    dentistName: 'Dra. Karine Ramos',
    procedureDone: 'Clareamento a Laser em Consultório',
    clinicalNotes: 'Aplicação de gel clareador peróxido de hidrogênio 35% com barreira gengival fotopolimerizável. Evolução de 3 tons na escala VITA.',
    prescriptions: ['Analgesico para sensibilidade: Paracetamol 750mg se houver desconforto.'],
    cost: 650,
  },
];

// Initial default tooth conditions map for teeth 11-18, 21-28, 31-38, 41-48
export function generateDefaultTeeth(): ToothCondition[] {
  const teethNumbers = [
    // Quadrante Superior Direito (18-11)
    18, 17, 16, 15, 14, 13, 12, 11,
    // Quadrante Superior Esquerdo (21-28)
    21, 22, 23, 24, 25, 26, 27, 28,
    // Quadrante Inferior Esquerdo (38-31)
    38, 37, 36, 35, 34, 33, 32, 31,
    // Quadrante Inferior Direito (41-48)
    41, 42, 43, 44, 45, 46, 47, 48
  ];

  return teethNumbers.map(num => {
    if (num === 16) {
      return { toothNumber: num, status: 'Em Tratamento', procedure: 'Restauração', notes: 'Cárie oclusal tratada com resina A2', dateUpdated: '2026-07-22' };
    }
    if (num === 26) {
      return { toothNumber: num, status: 'Atenção', procedure: 'Canal', notes: 'Indicado canal endodôntico', dateUpdated: '2026-07-20' };
    }
    if (num === 36) {
      return { toothNumber: num, status: 'Tratado', procedure: 'Coroa', notes: 'Coroa de porcelana colocada em 2023', dateUpdated: '2023-11-10' };
    }
    return { toothNumber: num, status: 'Saudável', procedure: 'Nenhum' };
  });
}
